---

- name: Configure Application Logs Logrotate Config
  become: yes
  template:
    dest: /etc/logrotate.d/application_logs
    src: application_logs.logrotate.d.j2
  when: sansible_logrotate_application_logs_paths != []

- name: Configure Custom Logrotate Configs
  become: yes
  template:
    dest: "/etc/logrotate.d/{{ item.name }}"
    src: custom_logs.logrotate.d.j2
  with_items: "{{ sansible_logrotate_custom_configs }}"
