---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: logrotate
      sansible_logrotate_application_logs_delete_rotated_logs: yes
      sansible_logrotate_application_logs_rotate_size: 100K
      sansible_logrotate_application_logs_paths:
        - /var/log/test_one.log
        - /var/log/test_two.log
      sansible_logrotate_custom_configs:
        - name: test_three
          path: /var/log/test_three/*.log
          options:
            - daily
            - missingok
            - rotate 7
            - compress
            - delaycompress
            - notifempty
            - sharedscripts
          scripts:
            postrotate: service rsyslog restart
