---

driver:
  name: docker

platforms:
  - name: sansible-logrotate-xenial
    image: ubuntu:xenial
  - name: sansible-logrotate-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 molecule/

scenario:
  name: default

verifier:
  name: testinfra
