---

driver:
  name: docker

platforms:
  - name: sansible_logrotate-trusty
    image: ubuntu:trusty
  - name: sansible_logrotate-xenial
    image: ubuntu:xenial
  - name: sansible_logrotate-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint

dependency:
  name: galaxy

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
